### ISSUE TITLE
About object detection in this article

### ISSUE THREAD

**Issue by yulei1234** [Mephisto405/Learning-Loss-for-Active-Learning#3]
Your work is good! Is there any recurrence of the experiment on target detection? I think it will be much more complicated than classification.

**Comment by Mephisto405** [comment]
Hi, thanks for your attention. Unfortunately, I have no concrete plan to reproduce other experiments (e.g., object detection) presented in this paper yet. Since I have only one GPU, it can take more than hours to train heavier tasks than an image classification task. Since I can't spend much time due to other research works, additional reproducing seems hard right now. Sorry!
